# Generated by Django 4.0.10 on 2024-03-15 23:05

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_due_date_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
